/*
 * Copyright (C) 2016/2020 Litote
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.jershell.kbson

internal enum class STATE {
    NAME, VALUE
}

internal class StateMap: Iterator<STATE> {
    var toggleState = false
    override fun hasNext(): Boolean = false

    override fun next(): STATE {
        toggleState = !toggleState
        return when(toggleState) {
            true -> STATE.NAME
            false -> STATE.VALUE
        }
    }
}